### ISSUE TITLE
Unable to parse all elements from the tree

### ISSUE THREAD

**Issue by rdudacz** [irobayna/stupidedi#122]
Hello,

I have this structure (it's anonymized):
```
ISA*00*          *00*          *AA*OOPPOO       *02*ABCD           *523126*1536*U*00401*000000002*0*T*>~
GS*SM*216236236*ABCD*52315*1536*2*X*004010~
ST*204*0002~
B2**ABC**12345678*L*PP*L~
B2A*00~
G62*64*20160427*1*0900*LT~
N1*SH*Co123*93*123123~
N3*PO Box 331122~
N4*City*ST*12345-6789*USA~
G61*SH*some text*TE*some text 2~
N7**0*90.50*G****22331*E**RT****10000~
S5*1*CL*11331*L*666*CA*999.99*E~
L11*353462472347*SI~
L11*52353*PO~
G62*10*20160101*I*0000*LT~
G62*10*20160101*K*2359*LT~
NTE*ADD*3~
N1*SF*CITYYY*93*444333~
N3*some address~
N4*city*state*postal*country~
G61*SH*texttt*TE*text 2~
```

And my problem is that I cannot extract all the elements from segments. Eg. I am trying to fetch the segment `N1*SF*CITYYY*93*444333~`.

parser.first.tap do |isa|
```
  isa.iterate(:GS) do |gs|
    stt = gs.find(:ST)
    stt.flatmap{|x| x.find(:N1, 'SF') } # parser doesn't open this segment
      .tap do |n1|
        n1.iterate(:N3) do |n3|
	  puts 'N3 SF:'
	  puts "#{n3.element(1).map(&:node).fetch(0)}" # it doesn't print anything
	end
      end

    stt.flatmap{|x| x.find(:N1, 'SH') } # parser opens this one
      .tap do |n1|
        n1.iterate(:N3) do |n3|
	  puts 'N3 SH:'
	  puts "#{n3.element(1).map(&:node).fetch(0)}" # it prints out data
	end
      end
```
      
Why it doesn't print/find the element `N1*SF`, but it only does the `N1*SH` one? (I also tried to switch the blocks, but the same result)

After a lot of trying outs and tests, I was able to print out the `N1*SF` segment using this approach:
```
stt.flatmap{|x| x.find(:S5) }
  .tap do |m|
    puts '18. N1:'
    el(m.find(:N1, 'SF'), 1, 2, 3, 4){|a, b, c, d| 
      puts "#{a}, #{b}, #{c}, #{d}"; 
    }
  end
```
But the problem here is that I don't know how to get from this element to the next ones - childrens `N3` and `N4`.

How can I successfully parse out the data from the tree?

Thank you!

**Comment by irobayna** [comment]
@rdudacz 

Rule of thumb should be,  If ```edi-pp``` is able to parse your transaction then the problem is how to code the parsing, navigation.  You did confirm this was happening correct?

I would suggest to get a copy of your specific EDI implementation guide for this transaction which will describe how to parse it.

if you look at the sample code from the previous issue, I would start off as simple as possible (no flatmap, el,  etc)  and then use something like this:

```ruby
            st.find(:N9, 'PG').map do |n9|
              @business_type = "#{n9.element(2).map(&:node).fetch(0)}"
            end
```
and making sure within your loops (```.iterate```) you print ```successors``` so you are sure the tree is being traverse properly.

**Comment by rdudacz** [comment]
@irobayna yes, it's valid,  I am able to parse the file with `edi-pp`.

I must be overlooking something elementary, because I am unable to parse even this super simple structure with `.iterate`:
parser.first.tap do |isa|
    isa.iterate(:GS) do |gs|  # no error
    	puts '2. GS'
        puts "#{gs.element(6).map(&:node).fetch(0)}"
 	puts '-'

        gs.iterate(:ST) do |st| # no error
        	puts '3. ST:'
   		puts "#{st.element(1).map(&:node).fetch(0)}"
   		puts "#{st.element(2).map(&:node).fetch(0)}"
        	pp st.successors
  		puts '-'

  		st.iterate(:B2) do |b2|
        	        puts '4. B2:'
	   		puts "#{b2.element(1).map(&:node).fetch(0)}"
		   	puts "#{b2.element(2).map(&:node).fetch(0)}"
		   	puts "#{b2.element(3).map(&:node).fetch(0)}"
		   	puts "#{b2.element(4).map(&:node).fetch(0)}"
		   	puts "#{b2.element(5).map(&:node).fetch(0)}"
	        	pp b2.successors
		  	puts '-'
	        end
        end
    end
end

And the output: B2**ABC**12345678*L*PP*L~

> ...
> 4. B2:
> 
> ABC
> 
> 12345678
> L
> [InstructionTable(
>     1: Instruction[B2A: Set Purpose       ](pop: 0, drop: 1),
>     2: Instruction[L11: Business Instruc..](pop: 0, drop: 1),
>     3: Instruction[G62: Date/Time         ](pop: 0, drop: 3),
>     4: Instruction[MS3: Interline Inform..](pop: 0, drop: 4),
>     5: Instruction[PLD: Pallet Informati..](pop: 0, drop: 5),
>     6: Instruction[NTE: Note/Special Ins..](pop: 0, drop: 5),
>     7: Instruction[ N1: Name              ](pop: 0, drop: 6, push: LoopState),
>     8: Instruction[ N7: Equipment Detail..](pop: 0, drop: 7, push: LoopState),
>     9: Instruction[ S5: Stop Off Details  ](pop: 1, drop: 0, push: TableState),
>    10: Instruction[ L3: Total Weight and..](pop: 1, drop: 3, push: TableState),
>    11: Instruction[ SE: Transaction Set ..](pop: 1, drop: 3, push: TableState),
>    12: Instruction[ ST](pop: 2, drop: 0, push: TransactionSetState),
>    13: Instruction[ GE: Functional Group..](pop: 2, drop: 2),
>    14: Instruction[ GS](pop: 3, drop: 0, push: FunctionalGroupState),
>    15: Instruction[IEA: Interchange Cont..](pop: 3, drop: 2),
>    16: Instruction[ISA](pop: 4, drop: 0, push: InterchangeState),
>    17: Instruction[ISA](pop: 5, drop: 0, push: TransmissionState))]
> -
> /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:629:in `__find': B2 segment cannot be reached from the current state (Stupidedi::Exceptions::ParseError)
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:419:in `find'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:462:in `block in iterate'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:154:in `deconstruct'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:106:in `flatmap'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:460:in `iterate'
> 	from test_stupidedi3.rb:53:in `block (3 levels) in <main>'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:461:in `block in iterate'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:154:in `deconstruct'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:106:in `flatmap'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:460:in `iterate'
> 	from test_stupidedi3.rb:45:in `block (2 levels) in <main>'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:461:in `block in iterate'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:154:in `deconstruct'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:106:in `flatmap'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/builder/navigation.rb:460:in `iterate'
> 	from test_stupidedi3.rb:37:in `block in <main>'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:154:in `deconstruct'
> 	from /Users/adam/.rvm/gems/ruby-2.3.3/gems/stupidedi-1.2.15/lib/stupidedi/either.rb:129:in `tap'
> 	from test_stupidedi3.rb:21:in `<main>'

It's only the 4th segment (`BA`), that's supposed to be accessible from the "root", no nesting, but the parser ends with the error that the segment cannot be reached. `.successors` says it should be available too.

I am not sure what do you mean by getting a copy of the EDI implementation guide - it's a "classic" ASC X12, the documentation describes the meaning of the segments and elements, not how to parse them.

However, the biggest problem here seems to be that even though the `.successors` outlines the available segments from the current one, the parser cannot read them without an error message.

**Comment by kputnam** [comment]
One likely problem is 'iterate(:B2)'. I'm guessing B2 is not a repeating segment; since 'iterate' repeatedly calls 'find', the first time it does find a B2 but the next 'iteration' fails.

We could probably improve that error message by checking that the matching segment is actually repeating. 

This is also shown from the successors list: from B2, there is not another reachable B2. The error happens when 'iterate' tries to find the next B2.

So instead try using tap, map, or flatmap rather than iterate

**Comment by kputnam** [comment]
The pop, drop, and push fields indicate that reading a segment will either pop the current state (usually terminate a child subtree and go back up to the parent), drop some succesor states (usually skipping some sibling nodes), or push a new state (usually a 'child' subtree)

**Comment by rdudacz** [comment]
`One likely problem is 'iterate(:B2)'. I'm guessing B2 is not a repeating segment; since 'iterate' repeatedly calls 'find', the first time it does find a B2 but the next 'iteration' fails.
`
I just tried to call `iterate(:N1)`, which occurs twice in the  204 file and getting the same error as for the `B2` segment.

Also, I was able to grab the `N1:SF` element, but it was more of a luck:
```
stt.flatmap{|x| x.find(:S5) }
	.tap do |m|
		puts '18. N1:'
            	# THIS WORKS - but how do I grab from this N1:SF the successor N3 (and N4)? 
            	el(m.find(:N1, 'SF'), 1, 2, 3, 4){|a, b, c, d| 
            	    puts "#{a}"; puts "#{b}"; puts "#{c}"; puts "#{d}";
            	 }

                 # THIS DOES NOT WORK
            	m.find(:N1, 'SF') do |n1|
		       		puts '16. N1::'
			   		puts "#{n1.element(1).map(&:node).fetch(0)}"
			   		puts "#{n1.element(2).map(&:node).fetch(0)}"
			   		puts "#{n1.element(3).map(&:node).fetch(0)}"
			   		puts "#{n1.element(4).map(&:node).fetch(0)}"
			   		puts "#{n1.element(5).map(&:node).fetch(0)}"
			   		puts '-'
			   	end
            	puts '-'
            end
```

The problematic element `N1:SF` - I was able to get it through
```
el(m.find(:N1, 'SF'), 1, 2, 3, 4){|a, b, c, d| 
  puts "#{a}"; puts "#{b}"; puts "#{c}"; puts "#{d}";
}
```
But how do I get from this `el` a successor segment?

Also, I tried to pull the `N1:SF` through `m.find(:N1, 'SF') do |n1|` - but the parser doesn't find it - even though based on the list of successors, it should.

**Comment by kputnam** [comment]
If you haven't read this document already, it should help: http://www.rubydoc.info/github/irobayna/stupidedi/master/file/doc/Navigating.md -- you can also view it in the GitHub repo in 'doc' but for some reason the images aren't displayed. I think the diagrams will be key for helping you.

**Comment by kputnam** [comment]
Also it's totally fine to traverse the tree using whatever method you like. The API is designed the way it is so that the parse tree and cursors pointing to locations in the tree are immutable: you can pass them around your code base without worrying that they will destructively update the parse tree; the other consideration is to make sure ordinary conditions like not finding an optional segment, are handled explicitly, and won't become runtime errors (eg, #blah called on NilClass). Some of this is explained in the above document (Navigating.md).

But I'm sure @irobayna's experience is common, that getting everyone on a team to learn something that's foreign to most Ruby APIs might be a hassle, so you might ask him for tips on how he uses stupidedi.
